module:
  mounts:
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts

# Default
permalinks:
  statutes: /team/expertises/:slug/
taxonomies:
  persons_expertise: persons_expertises
