module:
  mounts:
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts

# Default
permalinks:
  persons_expertises: /team/expertises/:slug/
  section: 
    persons_expertises: /team/expertises/
taxonomies:
  persons_expertise: persons_expertises
